### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Volt-0001** [tygerfox/steamiconrecovery#1]
hello, im trying to use the script but it does nothing, it simply opens itself and then closes

**Comment by tygerfox** [comment]
Is the "genicons.ps1" script located inside a folder with the game shortcuts in it?
Are the icons of the shortcuts actually missing from "C:\Program Files (x86)\Steam\steam\games"?

Try first opening the terminal by pressing right click and selecting "Open in Terminal" in the folder containing the "genicons.ps1" script. Then type ".\genicons.ps1" and press enter. The script should then run inside the terminal, without the terminal automatically closing, so you can see the output even after the script has finished.

Please let me know if the script works for you and what the output of the script is.

If PowerShell refuses to run the script have a look at [this](https://superuser.com/questions/106360/how-to-enable-execution-of-powershell-scripts) forum post to find out how to unlock unsigned PowerShell scripts.

**Comment by Volt-0001** [comment]
thanks for answering.
Sorry to bother you with a stupid problem. its seem i had not done the unsigned part correctly.
i used 
"set-executionpolicy remotesigned" 
when i should have used "Set-ExecutionPolicy unrestricted"

also this script is wonderful! i just got all my icons back!

**Comment by tygerfox** [comment]
No problem. I'm glad it's working for you.
